# Generated by Django 4.0.4 on 2022-05-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deptartments',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('departments', models.CharField(blank=True, db_column='Departments', max_length=30, null=True)),
            ],
            options={
                'db_table': 'deptartments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpDept',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('salary', models.IntegerField(blank=True, db_column='Salary', null=True)),
                ('start_date', models.DateField(blank=True, db_column='Start_Date', null=True)),
            ],
            options={
                'db_table': 'emp_dept',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=30, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=30, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=20, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
    ]
